on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

concurrency:
  group: "deploy-to-pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-pages-artifact@v1
        with: { path: "dist" }

      - uses: actions/deploy-pages@v2
        id: deployment
